name: Deploy Bastion Infrastructure

on:
  push:
    branches:
      - main # Triggers the workflow every time you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          # Vocareum environments usually operate in us-east-1
          aws-region: us-east-1


      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: Bastion-Host-Stack
          template: bastion.yaml
          no-fail-on-empty-changeset: "true"
          parameter-overrides: >
            KeyName=vockey,
            AvailabilityZone=us-east-1
